services:
  open-webui:
    image: faisalalanqood/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui-data:/app/backend/data
    ports:
      - 3000:8080
    environment:
      # Change this to your external Ollama URL
      - 'OLLAMA_BASE_URL=http://your-ollama-host:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped

volumes:
  open-webui-data: {} 